#!/bin/sh

rm -f ./pyphy/*.pyc 

echo "Removing so files from ./pyphy/Conversions"
rm ./pyphy/Conversions/_Conversions.so*

echo "Removing so files from ./pyphy/DataMatrix"
rm ./pyphy/DataMatrix/_DataMatrixBase.so*

echo "Removing so files from ./pyphy/Likelihood"
rm ./pyphy/Likelihood/_LikelihoodBase.so*

echo "Removing so files from ./pyphy/Phylogeny"
rm ./pyphy/Phylogeny/_Phylogeny.so*

echo "Removing so files from ./pyphy/ProbDist"
rm ./pyphy/ProbDist/_ProbDist.so*

echo "Removing so files from ./pyphy/ReadNexus"
rm ./pyphy/ReadNexus/_ReadNexus.so*

echo "Done."
