//tucson2005: these definitions needed by OmniORB and not provided automatically by VC7

#ifndef __x86__
#	define __x86__
#endif

#ifndef __WIN32__
#	define __WIN32__
#endif

//tucson2005: these VC7 warnings were being generated by OmniORB
//  warning C4311: 'type cast' : pointer truncation from 'char *' to '_CORBA_Sequence_String::ptr_arith_t'
//  warning C4312: 'type cast' : conversion from '_CORBA_Sequence_WString::ptr_arith_t' to '_CORBA_WChar *' of greater size
//  warning C4267: 'initializing' : conversion from 'size_t' to '_CORBA_ULong', possible loss of data
#pragma warning( disable : 4311 4312 4267)

//tucson2005: ACE_THROW_SPEC macro not defined in ConfigDependentHeaders.h unless CIPRES_USING_OMNI_ORB is defined
#ifndef CIPRES_USING_OMNI_ORB
#	define CIPRES_USING_OMNI_ORB 1
#endif
