#!/bin/tcsh

echo "Running autoheader..."
autoheader
echo 
echo "Running aclocal..."
aclocal
echo 
echo "Running autoconf..."
autoconf
echo 
echo "Running libtoolize..."
libtoolize --automake
echo 
echo "Running automake..."
automake --add-missing
echo 
echo "Running configure..."
chmod +x configure
setenv CXXFLAGS "-g -O3 -ftemplate-depth-25"
# setenv CXXFLAGS "-O3 -xN"
#./configure LOKIDIR=`pwd`/ NCLDIR=`pwd`/ BOOSTDIR=`pwd`/../boost_1_30_0 ACEDIR=`pwd`/../ACE_wrappers ACELIBDIR=`pwd`/../ACE_wrappers/lib TAODIR=`pwd`/../ACE_wrappers/TAO ORBSVCSDIR=`pwd`/../ACE_wrappers/TAO/orbsvcs --prefix=`pwd`
./configure LOKIDIR=$LOKI_ROOT NCLDIR=`pwd`/ BOOSTDIR=$BOOST_ROOT ACEDIR=$ACE_ROOT ACELIBDIR=$ACE_ROOT/lib TAODIR=$TAO_ROOT ORBSVCSDIR=$TAO_ROOT/orbsvcs --prefix=`pwd`
