// -*- C++ -*-
//
// $Id: CipresI.cpp,v 1.2 2005/05/18 14:06:10 liebowit Exp $

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1030

//#include "/Users/mholder/Documents/projects/Phycas/phycasdev/phycas/corba/interfaces/tree_merger//CipresI.h"
#include "CipresI.h"

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_is.cpp:52

// Implementation skeleton constructor
CipresIDL_Scriptable_i::CipresIDL_Scriptable_i (void)
{
}

// Implementation skeleton destructor
CipresIDL_Scriptable_i::~CipresIDL_Scriptable_i (void)
{
}
 
// TAO_IDL - Generated from
// be/be_visitor_operation/operation_is.cpp:57

char * CipresIDL_Scriptable_i::getUIXml (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  return CORBA::string_dup("");
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_is.cpp:57

CORBA::Boolean CipresIDL_Scriptable_i::execute (
    const char * command,
    CORBA::String_out display
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
   return CORBA::Boolean(true);
}

