// -*- C++ -*-
//
// $Id: CipresI.h,v 1.1 2005/03/08 03:22:13 mholder Exp $

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:969

#ifndef _USERS_MHOLDER_DOCUMENTS_PROJECTS_PHYCAS_PHYCASDEV_PHYCAS_CORBA_INTERFACES_TREE_MERGER__CIPRESI_H_
#define _USERS_MHOLDER_DOCUMENTS_PROJECTS_PHYCAS_PHYCASDEV_PHYCAS_CORBA_INTERFACES_TREE_MERGER__CIPRESI_H_

#include "CipresS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ih.cpp:57

class  CipresIDL_Scriptable_i : public virtual POA_CipresIDL::Scriptable
{
public:
  //Constructor 
  CipresIDL_Scriptable_i (void);
  
  //Destructor 
  virtual ~CipresIDL_Scriptable_i (void);
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ih.cpp:43
  
  virtual char * getUIXml (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Boolean execute (
    const char * command,
    CORBA::String_out display
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));
};


#endif /* _USERS_MHOLDER_DOCUMENTS_PROJECTS_PHYCAS_PHYCASDEV_PHYCAS_CORBA_INTERFACES_TREE_MERGER__CIPRESI_H_  */
