// -*- C++ -*-
//
// $Id: TreeMergeI.h,v 1.2 2005/05/18 14:06:10 liebowit Exp $

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be/be_codegen.cpp:969

#ifndef _USERS_MHOLDER_DOCUMENTS_PROJECTS_PHYCAS_PHYCASDEV_PHYCAS_CORBA_INTERFACES_TREE_MERGER__TREEMERGEI_H_
#define _USERS_MHOLDER_DOCUMENTS_PROJECTS_PHYCAS_PHYCASDEV_PHYCAS_CORBA_INTERFACES_TREE_MERGER__TREEMERGEI_H_

#include "TreeMergeS.h"
#include "LifeCycle_i.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ih.cpp:57

// todo: may want to implement LifeCycle differently.  I just put
// this in here to get things built.  Terri
class  CipresIDL_TreeMerge_i : public virtual POA_CipresIDL::TreeMerge,
	public virtual CipresIDL_LifeCycle_i 
{
public:
  //Constructor 
  CipresIDL_TreeMerge_i (void);
  
  //Destructor 
  virtual ~CipresIDL_TreeMerge_i (void);
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ih.cpp:43
  
  virtual ::CipresIDL::Tree * mergeTrees (
      const CipresIDL::TreeSeq & trees
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual char * getUIXml (
    
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ih.cpp:43

virtual CORBA::Boolean execute (
    const char * command,
    CORBA::String_out display
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ));
};


#endif /* _USERS_MHOLDER_DOCUMENTS_PROJECTS_PHYCAS_PHYCASDEV_PHYCAS_CORBA_INTERFACES_TREE_MERGER__TREEMERGEI_H_  */
