module cipresCORBA {
		// exception raised when a new handler object cannot be created
	exception X_CreateObjException {};
	
		//  exception raised when an illegal tree specification is sent 
		//	to a tree-dependent method (e.g. drawTree)
	exception X_InvalidTree {};
	
		// Forward declaration the TreeDrawer interface so that the TreeDrawer_Factory can refer to it
	interface TreeDrawer;
	
		//   A factory class for the TreeDrawer interface
	interface TreeDrawerFactory {
			//	Return the TreeDrawer interfaces (eventually this may need an argument for initialization)
		TreeDrawer getTreeDrawer ()
		  raises (X_CreateObjException);
	};
	
	interface TreeDrawer {
			//	Executes the command and returns the output as a string
		string execute(in string command);
			//	Displays the tree graphically
		void drawTree(in string newickTree)
		  raises (X_InvalidTree);
	};
};