#!/bin/sh

if [ -n $PYTHON_ROOT ]
then
	echo PYTHON_ROOT=$PYTHON_ROOT
else
	echo Please define PYTHON_ROOT environmental variable as path to Python24 directory
	exit 0
fi

# export PATH=.:$HOME/local/bin:/usr/local/condor/bin:$PATH
# export PYTHON_VERSION=2.4
# export DYLD_LIBRARY_PATH=$HOME/phycasdev/pyphy/bin/boost/libs/python/build/libboost_python.dylib/darwin/release/shared-linkable-true
# export CVS_RSH=/usr/bin/ssh
# export BOOST_ROOT=$HOME/boost_1_33_1
# export CIPRES_LIB_ROOT=$HOME/cipres/framework
# export PYTHONPATH=$HOME/site-packages/numarray:$HOME/phycasdev/pyphy/pyphy:$HOME/phycasdev/pyphy/apps:$HOME/phycasdev/python
# export PYTHON_ROOT=/Library/Frameworks/Python.framework/Versions/2.4

# export PHYCAS_ROOT=$HOME/phycasdev
# export NCL_ROOT=$HOME/phycasdev
# export BUILD=release
# export TOOLS=darwin
# bjam -q
