#include "Client.idl"

module cipresCORBA
{
  interface TreeDatabase
  {
	  typedef sequence <string> stringArray;
	  typedef string taxaContext;
	  
	  string 	execute(in string command);

	  void 		setClient(in Client client_param);
	  void 		disconnect();
	  
	  taxaContext 	findOrSetTaxa(in stringArray taxa);
	  long 			getNumberOfTrees(in taxaContext taxaID);
	  void 			putTree(in taxaContext taxaID, in string tree);
	  string 		getTree(in taxaContext taxaID, in long whichTree);
	  string 		getDatabaseName();
  };

  interface TreeDBFactory
  {
	  TreeDatabase build();
  };
};
